pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                script {
                    // Set up environment variables
                    env.JD_TO_RUN = 'maven:3.8.1-adoptopenjdk-11'
                    env.JD_TO_PULL = 'maven:3.8.1-adoptopenjdk-11'
                }
                sh 'docker inspect -f . "$JD_TO_RUN" || docker pull "$JD_TO_PULL"'
                sh 'mvn clean install'
            }
        }
    }
}

